### ISSUE TITLE
Add 4get

### ISSUE THREAD

**Issue by AsmodeumX** [NoPlagiarism/instances-list#13]
https://git.lolcat.ca/lolcat/4get
https://4get.ca/instances

**Comment by NoPlagiarism** [comment]
Thanks. I'll look into it

IG, gonna use instances list from official got repo

Leaving PHP file with instances to parse
https://git.lolcat.ca/lolcat/4get/src/branch/master/data/config.php#L56

Raw: `https://git.lolcat.ca/lolcat/4get/raw/branch/master/data/config.php`

P.S: Used `https://4get.ca/ami4get`

**Comment by NoPlagiarism** [comment]
Added Clearnet domains
