### ISSUE TITLE
vixip

### ISSUE THREAD

**Issue by TechnicalSuwako** [NoPlagiarism/instances-list#7]
https://pixiv.owacon.moe/
https://gitler.moe/suwako/vixip

**Comment by NoPlagiarism** [comment]
Thanks for the issue
I won't do it now, but leave it open, until

- [ ] Till there will be at least 2-3 instances (What's meaning of subfolder for only one instance?)
- [ ] It get's reviewed or partly reviewed (better added) in https://github.com/digitalblossom/alternative-frontends/issues/68 or/and https://github.com/mendel5/alternative-front-ends/issues/171 or/and https://github.com/libredirect/browser_extension/issues/693
- [x] Talk with myself about gitler.moe... ~~Like, wtf is this? Sounds cancellable as hell~~ Strange, but stable(?) gitea instance
- [ ] (OPTIONAL) English translation of ~~ReadMe~~ all service would be nice

**Comment by NoPlagiarism** [comment]
Closing for now, cuz still no instances
